### ISSUE TITLE
Use bootstrap table for database and table lists

### ISSUE THREAD

**Issue by clach04** [clach04/SQLshite#27]
Better finger/touch UI (larger finger target)

**Comment by parag477** [comment]
I want to work on this?

**Comment by clach04** [comment]
> I want to work on this?

Hi @parag477 , I somehow missed this when you added this, sorry for the late reply. Is this something you were interested in adding?

This project is a little chaotic at the moment (for example missing error handling in a few places) but I'd certainly be interested in seeing a PR. No problem if you are not, I can get this completed in a few minutes when I get some down time.
